### ISSUE TITLE
Deploy the simplest ever smart contract on Polygon blockchain and interact with it

### ISSUE THREAD

**Issue by sumeetpareek** [sumeetpareek/stoner-cat-baxster-the-hackster#1]
## TASK (from end users perspective)

- `As (stakeholder X), I want to do (this Y thing), so that I can (be unblocked for this next Z thing)`
- As Sumeet's entrepreneurial friend and mentor — I want a link to his first test smart contract along with notes on what to do with it — so that I can start getting familiar with blockchain explorers, decentralised apps (Dapps), programmable money, etcetera.

## DONE WHEN

- [ ] crypto contract with callable functions is deployed on polygon testnet chain
- [ ] friends and mentors are reached out to try interacting with the smart contract 

## CHECKLIST 

- [ ] login to polygon testnet .. https://mumbai.polygonscan.com/
- [ ] find and follow polygon developer docs .. https://docs.matic.network/docs/develop/getting-started/
- [ ] item
- [ ] item
- [ ] item

**Comment by sumeetpareek** [comment]
## WORK LOG 

extremely sporadic work done in many micro sessions
cuz wife and i have baby on the way (anytime now)
and we are at a friends 30th birthday party 

and mini sessions
mumbai testnet does not have a sign in button
https://mumbai.polygonscan.com/
only the mainet does 
https://polygonscan.com/

footer of the testnest has a **Add Mumbai Network** to metamask button
todo try later

tutorials are not good for quick start
https://docs.matic.network/docs/develop/getting-started/#-building-a-new-dapp-on-matic
dont wanna clone full airbnb to deploy simplest of contracts
https://docs.matic.network/docs/develop/full-stack-dapp-with-pos/

paid advance to keerthi
https://twitter.com/SumeetOlivier/status/1421469791148204032
todo follow up on the code evaluation task

renamed simple storage contract to `Sumeet001Storage`
understood functions and some solidity constructs
pragma <xyz> is a way to send specific instructions to the compiler
complied contract
this created json artifacts with lots of metadata stuff

renamed contract in `deploy_web3.js` script
it reads associated json file
and uses that to deploy contract

running deploy script gave error 
`ParserError: Expected pragma, import directive or contract/interface/library/struct/enum/constant/function definition.`
![image](https://user-images.githubusercontent.com/140441/127780378-1f8e32c9-fbd0-4cf3-b260-d3ddd2da2cca.png)

from remix Home 
download all files 
gave a zip but it was empty

✅  was able to deploy and run within sidebar .. but not via metamask wallet to a test chain 
⛔  web3 deploy sprint would not run, with console error `Unhandled promise rejection Error: scriptRunner plugin is already rendered`


## GOOD LINKS

simple counter deploy from shobhit looks good
https://www.youtube.com/watch?v=d5YHnDZNCPU&ab_channel=Shobhit
polygon docs on using remix
https://docs.matic.network/docs/develop/remix/
figment learning but uses truffle
https://learn.figment.io/network-documentation/matic/polygon-matic-pathway/deploy-a-solidity-smart-contract

minting tool to try later
https://mintnft.today/
from
https://discord.com/channels/635865020172861441/826371674152370182/868620056156860476

https://medium.com/pinata/how-to-create-layer-2-nfts-with-polygon-and-ipfs-aef998ff8ef2
from 
https://discord.com/channels/635865020172861441/826371674152370182/867800080396320808


## Social Discipline

check about sale of animal world war
https://animalworldwar.io/#Buy

tracking of NFT floors and overall NFT space
https://twitter.com/LeBoredJames/status/1421867712171548675

```
The rarest attribute of every Stoner Cat is the stoner cat ID. 
Each ID is unique and only one cat has it. 
That's 0.009596928983 % rarity.
Insanely, I know!!!
```
